apiVersion: v1
kind: Service
metadata:
  name: db
  lables:
    name: db-service
    app: demo-voting-pod
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgress-pod
    app: demo-voting-pod
