apiVersion: v1
kind: Service
metadata:
  name: redis
  lables:
    name: redis-service
    app: demo-voting-pod
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-service
    app: demo-voting-pod
